### PR TITLE
fix(button): apply first-time `style` patches and clear stale `style` internals

### LINKED ISSUE #6118: Unsetting `Button.bgcolor` does not work
### Discussed in https://github.com/flet-dev/flet/discussions/6112

<div type='discussions-op-text'>

<sup>Originally posted by **AquamarineCyan** February  2, 2026</sup>
### Question

When I updated `button.bgcolor` from `None` to other colors, I did not receive any changes, including in the `ButtonStyle`. But in the `Container`, everything is normal.

button_bgcolor_error

### Code sample

```python
import flet as ft

ft.context.disable_auto_update()


def main(page: ft.Page):
    def change_button_bgcolor():  # do not work
        if button.bgcolor is None:
            button.bgcolor = ft.Colors.GREEN
        else:
            button.bgcolor = None
        button.update()

    def change_button_bgcolor_if_yellow():  # work
        if button.bgcolor is ft.Colors.YELLOW:
            button.bgcolor = ft.Colors.GREEN
        else:
            button.bgcolor = ft.Colors.YELLOW
        button.update()

    def change_button_style_bgcolor():
        if button.style is None or button.style.bgcolor is None:
            if button.style is None:
                button.style = ft.ButtonStyle(bgcolor=ft.Colors.GREEN)
            else:
                button.style.bgcolor = None  # do not work
        else:
            button.style.bgcolor = None
        button.update()

    def change_container_bgcolor():
        if container.bgcolor is None:
            container.bgcolor = ft.Colors.RED
        else:
            container.bgcolor = None
        container.update()

    button = ft.Button(
        "Click me to change bgcolor",
        # bgcolor=None,
        on_click=change_button_bgcolor,
        # on_click=change_button_style_bgcolor,
        # ------
        # bgcolor=ft.Colors.YELLOW,
        # on_click=change_button_bgcolor_if_yellow, # it work
    )

    container = ft.Container(
        ft.Text("Click me to change bgcolor"),
        bgcolor=ft.Colors.YELLOW,
        width=200,
        height=50,
        on_click=change_container_bgcolor,
    )

    page.add(button, container)


if __name__ == "__main__":
    ft.run(main)
```

### PR DESCRIPTION
**Pull request by ndonkoHenri**
Fix #6118

## Description
When a `Button` starts without `bgcolor`, the first click (`None -> GREEN`) could update Python state but not the UI.  
Also, after changing style props back to defaults, stale style data could remain and keep old visuals.

### Root cause
1. **Dart patch apply path**
   - First-time style updates arrive as an ADD patch to `_internals.style`.
   - If `_internals` didn’t exist yet, patch target resolution failed to materialize missing intermediate maps.

2. **Python control internals**
   - `Button` / `IconButton` wrote `_internals["style"]` when style-related props were set,
   - but didn’t clear it when props returned to defaults.

### Changes
- **Dart**
  - Enhanced `getPatchTarget(...)` with optional `createMissingMaps`.
  - ADD operations now resolve targets with `createMissingMaps: true`, allowing creation of missing intermediate maps (e.g. `_internals`) before inserting new keys.
 
- **Python**
  - Clear stale style internals when style-driving values are default:
    - `self._internals.pop("style", None)`

## Summary by Sourcery

Ensure button style patches correctly materialize intermediate state and clear stale style metadata.

Bug Fixes:
- Fix JSON patch ADD operations so missing intermediate maps (e.g., control internals) are created before inserting new entries, ensuring initial style updates apply to controls like Button.
- Clear stale style internals for Button and IconButton when style-driving properties return to default values so visuals revert correctly.

Tests:
- Add a control patching test to verify ADD operations create missing intermediate maps in control properties.

### CODE REVIEW

File: packages/flet/lib/src/models/control.dart [hunk 1]
```diff
@@ -331,15 +331,33 @@ class Control extends ChangeNotifier {
...
+    getPatchTarget(int index, {bool createMissingMaps = false}) {
       var path = pathIndex[index]!;
       dynamic obj = this;
       Control? control = this;
       for (var p in path) {
         if (obj is Control) {
-          obj = obj.properties[p];
+          var next = obj.properties[p];
+          if (next == null && createMissingMaps) {
+            next = <dynamic, dynamic>{};
```
Comment (FeodorFitsner) [inline packages/flet/lib/src/models/control.dart]: When there is missing "something", why it should be map, not a list or something else?

**Review by FeodorFitsner — APPROVED** [review]
